# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: match message
        run: |
          sudo apt install libxml-xpath-perl
          xpath -e '//testsuite/testcase/failure/text()' log/TEST-*.xml | sed ":a;N;s/\n//g;ta"
          export FAILURE_MESSAGE=`xpath -e '//testsuite/testcase/failure/text()' log/TEST-*.xml | sed ":a;N;s/\n//g;ta"`
          export ERROR_MESSAGE=`xpath -e '//testsuite/testcase/system-out/text()' log/TEST-*.xml | grep "Annotation Error Message"`
          export WARNING_MESSAGE=`xpath -e '//testsuite/testcase/system-out/text()' log/TEST-*.xml | grep "Annotation Warning Message"`
          export DEBUG_MESSAGE=`xpath -e '//testsuite/testcase/system-out/text()' log/TEST-*.xml | grep "Annotation Debug Message"`
          echo "::error::$FAILURE_MESSAGE"
          echo "::error::$ERROR_MESSAGE"
          echo "::warning::$WARNING_MESSAGE"
          echo "::debug::$DEBUG_MESSAGE"
          echo "::debug::this is a debug message."
          
      # Runs my Bash Script
      - name: Bash Script
        run: |
          sh .github/workflows/test.sh
